// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Bubble: typeof import('./src/components/bubble/bubble.vue')['default']
    BulkOperations: typeof import('./src/components/bulk-operations/index.vue')['default']
    Iframe: typeof import('./src/components/iframe/index.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutConventional: typeof import('./src/components/layout/src/layout-conventional.vue')['default']
    LayoutRightBtnGroup: typeof import('./src/components/layout-right-btn-group/index.vue')['default']
    LayoutSandwich: typeof import('./src/components/layout/src/layout-sandwich.vue')['default']
    LayoutTab: typeof import('./src/components/layout-tab/layout-tab.vue')['default']
    LayoutTabClose: typeof import('./src/components/layout-tab-close/layout-tab-close.vue')['default']
    LayoutTeambition: typeof import('./src/components/layout/src/layout-teambition.vue')['default']
    LayoutTop: typeof import('./src/components/layout/src/layout-top.vue')['default']
    ModalDrag: typeof import('./src/components/modal-drag/modal-drag.vue')['default']
    Setting: typeof import('./src/components/setting/setting.vue')['default']
    Table: typeof import('./src/components/table/index.vue')['default']
  }
}

export { }
