// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutConventional: typeof import('./src/components/layout/layout-conventional.vue')['default']
    LayoutFullScreen: typeof import('./src/components/layout/layout-full-screen.vue')['default']
    LayoutSandwich: typeof import('./src/components/layout/layout-sandwich.vue')['default']
    LayoutTeambition: typeof import('./src/components/layout/layout-teambition.vue')['default']
    LayoutTop: typeof import('./src/components/layout/layout-top.vue')['default']
    Setting: typeof import('./src/components/setting/setting.vue')['default']
  }
}

export { }
